### PR TITLE
- added support for passing bearer token as cookie

### PR DESCRIPTION
**Pull request by dmitriyblok**
- added support for introspection interval
- added support for passing request cookies on introspection call
- added passing introspection endpoint authorization method into openidc_call_token_endpoint call

### CODE REVIEW

**Comment by zandbelt** [comment]
lgtm

**Comment by bodewig** [comment]
Sorry, I'll need more time for a real review.

I think you can access cookie values directly via `ngx.var['cookie_'..COOKIE_NAME]` without us having to parse the header(s) ourselves. At least this is how I've done it myself in the past, but maybe there is a good reason to avoid it.

**Comment by dmitriyblok** [comment]
From what I understand parsing headers is more universal and will work in all cases whereas $cookie_COOKIE_NAME only works with alphanumeric cookies. https://stackoverflow.com/questions/26128412/how-to-extract-some-value-from-cookie-in-nginx

**Comment by bodewig** [comment]
I knew I'd lear something by asking, thanks :-)

The table indexing syntax works for me for cookie names containing dashes and lua-resty-session also uses `ngx.var['cookie_X']` for cookies containing underscores in their name (see https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session.lua#L143), so I guess this syntax is safe as opposed to `ngx.var.cookie_X`.

**Comment by dmitriyblok** [comment]
OK. I can change it to use ngx.var["cookie_X"]

**Comment by bodewig** [comment]
I wasn't aware of the existing options of `mod_auth_openidc` as I have never used that myself. Hans will probably have a better idea about names then :-)

For tests I really just run the two docker command from the bottom of the readme. The developer experience isn't nice, of course. The roundtrip of creating new docker image with every change is ugly and often I end up editing the test cases inside of the container until the tests pass. No better idea, I'm sorry.

**Comment by zandbelt** [comment]
well the net result of removing the introspection results from the cache is that the token will be introspected again, hence the repetition interval

**Comment by bodewig** [comment]
OK, fine with me. We can merge this now or wait for the REAME updates.

**Comment by dmitriyblok** [comment]
I have updated README with the new example and descriptions shamelessly stolen from mod_oauth_openidc :-)

**Comment by bodewig** [comment]
Many thanks!

I'm not sure "(can be configured on a per-path basis)" is quite true - of course you can use different opts for different locations, but that's true for all settings.

**Comment by dmitriyblok** [comment]
Ugh-ogh. Bad copy paste. Could you remove "(can be configured on a per-path basis)" from there? Thank you!

**Comment by bodewig** [comment]
tests added with eb8510c and abc780a and addressed some of my nits with e3ce0d1 and 5a9ac8e

It would be good if you could have a second look @dmitriyblok

**Pull request merged**
