### PR TITLE
Support form post response mode

### LINKED ISSUE #414: Support response_mode=form_post
This extension to OAuth 2.0 defines Form Post Response Mode:

https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html

The specification includes this summary in the first paragraph: "This specification defines the Form Post Response Mode. In this mode, Authorization Response parameters are encoded as HTML form values that are auto-submitted in the User Agent, and thus are transmitted via the HTTP POST method to the Client, with the result parameters being encoded in the body using the application/x-www-form-urlencoded format."

We are working with an OAuth provider which requires the use of Form Post Response Mode, and hope that it may be possible to use `lua-resty-openidc`. The problem is here:

https://github.com/zmartzone/lua-resty-openidc/blob/5ff02a65c5752c38b30d4d17b350ec97c52a2471/lib/resty/openidc.lua#L1085-L1094

You can see that when `lua-resty-openidc` processes an Authorization Response, it expects to find `code` and `state` parameters *in the URL query string*. However, with Form Post Response Mode, these parameters must be retrieved from the request body.

If the line which reads `local args = ngx.req.get_uri_args()` is adjusted to `ngx.req.read_body(); local args = ngx.req.get_post_args()`, then Form Post Response Mode seems to work as desired. It is also necessary to add `authorization_params = { response_mode="form_post" }` in `opts`.

Possibly related: #164 mentions something about `response_mode=form`, and was rejected. However, I believe the reason for rejecting that request was because the poster wanted to use `response_type=id_token`, which was deemed to be a less secure mode of operation.

If the maintainers agree with this request, I am happy to work on a PR.

### PR DESCRIPTION
**Pull request by bodewig**
closes #414

### CODE REVIEW

**Comment by alexdowad** [comment]
Dear maintainers, may I ask if this PR is likely to be merged soon?

**Comment by bodewig** [comment]
sorry I completely forgot to merge it - just wanted to show the updated docs before I went ahead. Thank you for the reminder.

**Comment by alexdowad** [comment]
Thanks very, very much!

Looking forward to the next release.

**Comment by alexdowad** [comment]
@bodewig @zandbelt Dear maintainers, please allow me to ask... is it likely you will cut a new release to get this feature out, or wait until a few more enhancements have been merged before the next release?

**Comment by bodewig** [comment]
@zandbelt could you please cast the necessary magic again?

**Comment by zandbelt** [comment]
> @zandbelt could you please cast the necessary magic again?

I'd rather wait for some more changes before doing a full release. I have not seen any demand for form post besides this one: I hope copying in the new openidc.lua file by hand is acceptable for the short term

**Comment by alexdowad** [comment]
> > @zandbelt could you please cast the necessary magic again?
> 
> I'd rather wait for some more changes before doing a full release. I have not seen any demand for form post besides this one: I hope copying in the new openidc.lua file by hand is acceptable for the short term

Understood. Thanks.

**Pull request merged**
