### PR TITLE
Fix zmartzone/lua-resty-openidc#157 : Update Id token in session afte…

### PR DESCRIPTION
**Pull request by grrolland**
This pull request update the id token in session after refreshing tokens with token endpoint. Finally, the content of the session is coherent (access token, refresh token, id token).

### CODE REVIEW

**Comment by bodewig** [comment]
I agree, in that case the PR looks good to me.

**Comment by zandbelt** [comment]
It would be great to include a test for it... (never thought I would say that ;-))

**Comment by bodewig** [comment]
I've pushed the PR, a small refactoring (please have a look at 11a9f26 @grrolland ) and tests to the pr-158 branch.

While thinking through the case where the token endpoint returns an invalid id token on refresh I feel the handling is inconsistent right now. `openidc_access_token` (correctly IMHO) returns an error in that case but we keep the access token stored inside the session. It seems we should remove all tokens from the session if we want to discard the token endpoint's response.

**Comment by zandbelt** [comment]
I don't see that last implication: whatever access token is returned from the token endpoint may be stored in the session; even if there's an error in a subsequent call to the token endpoint, we can still choose to preserve the old one under the assumption "if it still valid it is ok otherwise we'll find out sooner or later"

**Comment by bodewig** [comment]
As the current code stands the old access token has been replaced by the one that was returned from the token endpoint inside of the session. The inconsistency I see is that we don't return the access token because id token verification failed but we still store it inside the session. I'd be fine with either removing the access token completely or keeping the old one, but the current state feels wrong to me.

**Comment by zandbelt** [comment]
Ah right, I misunderstood at first but agree with you.

**Comment by bodewig** [comment]
What would be your preferred option, remove clear the tokens completely or restore the old ones?

I don't think the old ones will be useful as the refresh token has already been used by now and the access token has likely expired, so would opt for clearing the tokens.

**Comment by zandbelt** [comment]
Yeah, you're right: the reason for refreshing should be that the client can't use the existing access token so there should be no reason to keep it regardless of the result. That is different from the id_token.

**Comment by bodewig** [comment]
OK, I've changed the branch, see a968e76

**Comment by zandbelt** [comment]
So now the `id_token` is also set to `nil` where it doesn't  need to https://github.com/zmartzone/lua-resty-openidc/pull/158#issuecomment-389979084

**Comment by bodewig** [comment]
Ah, thanks, you are right. 551564f

**Comment by zandbelt** [comment]
the log message "ngx.log(ngx.ERR, "invalid id token, discaring refreshed id token")
" is off (+ a spelling error)

**Comment by bodewig** [comment]
Not sure I know what you mean with "off", see b27009f

Unfortunately I've got some second thoughts again, sorry for that. Wouldn't it be cleaner if we verified an id_token returned while refreshing regardless of whether we are going to store it inside the session? In that case we could treat it like a "normal" token refresh error and simply leave the whole session alone (see https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1090 ).

**Comment by bodewig** [comment]
regarding those latest thoughts see 13516c4 in yet another branch that I'll need to clean up once we are happy :-)

**Comment by bodewig** [comment]
merged, thanks @grrolland !

**Pull request merged**
