### PR TITLE
Do not fix lua-resty-jwt

### PR DESCRIPTION
**Pull request by kayano**
fixes https://github.com/zmartzone/lua-resty-openidc/issues/362

### CODE REVIEW

**Comment by kayano** [comment]
@zandbelt is it possible to check travis on PR?

**Review by ledbruno — APPROVED** [review]
we used this...seems ok

**Comment by kayano** [comment]
any chance to have it merged?

**Comment by kopernic-pl** [comment]
related/duplicate of #366 . But I'd want any of those two merged :)

**Comment by bodewig** [comment]
I didn't want to pick up your changes to the Travis config, that's why I didn't merge the PR directly. Thanks you.

**Comment by bodewig** [comment]
which of course was, before I saw Travis needed to be changed as lua-resty-jwt uses a version 3 rockspec, sorry.

**Pull request closed without merging**
