### PR TITLE
Added prohibit_redirect option to allow XHR to handle redirects

### PR DESCRIPTION
**Pull request by arcivanov**
Cleanup and optimize requires
Optimize duplicate code related to setting access tokens

### CODE REVIEW

**Comment by arcivanov** [comment]
@bodewig

**Comment by arcivanov** [comment]
@bodewig bump

**Comment by arcivanov** [comment]
@bodewig bump?

**Comment by zandbelt** [comment]
`unauth_action = deny` was designed to handle the case of not redirecting: this PR would duplicate the functionality for no good reason as far as I can see

the cleanup and un-duplicating of code is appreciated but would go better in separate PRs

**Comment by arcivanov** [comment]
@zandbelt would you be ok with extending the "unauth_action=deny" to the silent reauthentication as well? I don't really care either way what the option is called.

**Comment by arcivanov** [comment]
I'm talking about this condition:
https://github.com/zmartzone/lua-resty-openidc/pull/358/files#diff-1c5839bc51fa1aa064c7206dce60fb3eR1478
being added here: 
https://github.com/zmartzone/lua-resty-openidc/pull/358/files#diff-1c5839bc51fa1aa064c7206dce60fb3eR1504

**Comment by bodewig** [comment]
`prohibit_redirect` strongly overlaps with `unauth_action = 'deny'`. The only real difference is `prohibit_redirect` disables a premature token refresh if `refresh_session_interval ` is set. If you use `unauth_action='deny'` and `refresh_session_interval = nil` you get the exact same result AFAICT. So I believe the new option is redundant.

From an implementation POV you ignore the value of `prohibt_redirect`, it seems that setting it to `true` or `false` has the same effect.

**Comment by arcivanov** [comment]
Yep, managed to get it to work with those too. Withdrawn.

**Pull request closed without merging**
